repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.264'
  hooks:
    - id: ruff
      args: [--fix]
- repo: https://github.com/psf/black
  rev: "23.3.0"
  hooks:
    - id: black
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      args: ["-p", "hft2ane"]
      pass_filenames: false
      language: system
      types: [python]
      require_serial: true
