[tool.poetry]
name = "anetz"
version = "0.1.0"
description = "Apple Neural Engine-accelerated versions of any BERT-derived model on HuggingFace"
authors = ["Anentropic <ego@anentropic.com>"]
readme = "README.md"
license = "Apache 2.0"
packages = [{include = "anetz"}]

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.27.4"
ane-transformers = "^0.1.3"
torch = "*"
torchinfo = "*"
asitop = "^0.0.23"
beaupy = "^3.5.3"
art = "^5.9"

[tool.poetry.group.dev.dependencies]
ipython = "^8.12.0"
pdbpp = "^0.10.3"
mypy = "^1.2.0"
ruff = "^0.0.262"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
[[tool.mypy.overrides]]
module = [
    "ane_transformers.*",
    "asitop.*",
    "coremltools.*",
    "huggingface_hub.*",
    "transformers.*",
]
ignore_missing_imports = true
